FROM python:3.11-slim
LABEL python_version=python3.11

ENV PYTHONUNBUFFERED=1

RUN apt-get update

ENV POETRY_NO_INTERACTION=1
ENV POETRY_HOME=/opt/env
ENV POETRY_CACHE_DIR=/opt/.cache

ENV POETRY_VIRTUALENVS_IN_PROJECT=1

RUN python3 -m venv ${POETRY_HOME}
RUN ${POETRY_HOME}/bin/pip install -U pip setuptools
RUN ${POETRY_HOME}/bin/pip install poetry==2.1.3
ENV PATH=$PATH:${POETRY_HOME}/bin

COPY . /app/
WORKDIR /app

RUN poetry lock
ENV PATH="/app/.venv/bin:$PATH"